import 'dart:io';

import '../modules/lighting/lighting_module.dart';
import '../modules/security/security_module.dart';
import '../modules/transport/transport_module.dart';
import 'factories/module_factory.dart';
import 'builders/report_builder.dart';
import 'adapters/weather_adapter.dart';
import 'proxy/security_proxy.dart';
import 'singleton/logger.dart';

class CentralController {
  CentralController._internal() {
    _logger.log('Controller initialized');
  }

  static final CentralController _instance = CentralController._internal();
  static CentralController get instance => _instance;

  final _logger = Logger.instance;

  final _transport = ModuleFactory.create('transport');
  final _lighting = ModuleFactory.create('lighting');
  final _security = ModuleFactory.create('security');
  final _energy = ModuleFactory.create('energy');

  bool lightsOn = false;

  void showStatus() {
    print('\n--- SmartCity Status ---');
    _transport.status();
    _lighting.status();
    _security.status();
    _energy.status();
    print('--- end status ---\n');
  }

  void toggleLighting() {
    lightsOn = !lightsOn;
    (_lighting as LightingModule).setLights(lightsOn);
    _logger.log('Lights toggled: $lightsOn');
  }

  void requestTransportUpdate() {
    final weather = WeatherAdapter.getWeather();
    (_transport as TransportModule).update(weather);
    _logger.log('Transport updated with weather: $weather');
  }

  void requestSecureResource(String role) {
    final proxy = SecurityProxy(_security as SecurityModule);
    final allowed = proxy.requestAccess(role);
    print('Access allowed: \$allowed');
  }

  void buildAndPrintReport() {
    final builder = CityReportBuilder();
    builder
      ..setTitle('Daily SmartCity Report')
      ..addSection('Lighting', 'Lights: \$lightsOn')
      ..addSection('Transport', 'Transport status printed in console')
      ..addSection('Energy', 'Energy module status printed')
      ..setFooter('Generated by SmartCity System');

    final report = builder.build();
  }
}
